import 'dart:ui';
import 'package:flutter/material.dart';

class AppColor {
  static const Color defaultColor = Color(0xFF0B2088);
  static const Color yellowColor = Color(0xFFEEA100);
  static const Color defaultColor1 = Color(0x4D0B2088);
  static const Color redAlphaColor = Color(0xCCF44336);
  static const Color black20Color = Color(0x33000000);
  static const Color defaultDeepColor = Color(0xFF0A1C79);
  static const Color defaultLightColor = Color(0xFFC3D0FF);
  static const Color defaultLightColor2 = Color(0xFFE3E9FF);
  static const Color textColor = Color(0xFF0E0E0E);
  static const Color textColor2 = Color(0xFF333333);
  static const Color alphaColor = Color(0x1E000000);
  static const Color textColor1 = Color(0xFF515F84);
  static const Color greyColor = Color(0xFF4D4D4D);
  static const Color greyColor2 = Color(0xFF171717);
  static const Color backgroundColor = Color(0xFFF6F8FF);
  static const Color backgroundColor1 = Color(0xB3F6F8FF);
  static const Color chatColor = Color(0xFFE7E9F5);
  static const Color hintTextColor = Color(0xFF6A6A6A);
  static const Color buttonColor = Color(0xFF002AFF);
  static const Color seeAllColor = Color(0xFF2E47C7);
  static const Color savedColor = Color(0xFF040C35);
  static const Color linearColor = Color(0xFF000F5B);
  static const Color linearLightColor = Color(0xFF6294FF);
  static const Color linearShadowColor = Color(0x3F000000);
  static const Color buttonColor1 = Color(0xFF021681);
  static const Color containerColor = Color(0xFFE8E9F0);
  static const Color borderColor = Color(0xFFDAD9D9);
  static const Color boxShadowColor = Color(0x3F000000);
  static const Color boxShadowColor2 = Color(0x26000000);
  static const Color containerColor2 = Color(0xFFB4BBDF);
  static const Color containerColor3 = Color(0xFFE0E4F2);
  static const Color containerBorderColor = Color(0xFFB5B5B5);
  static const Color disableColor = Color(0xEEEEEEFF);
  static const Color otpColor = Color(0xFFDBDEEF);
  static const Color orangeColor = Color(0xFFB26E20);
  static const Color greenColor = Color(0xFF4DB131);
  static const Color greenColor2 = Color(0xFF96DC42);
  static const Color blackColor = Color(0xFF000000);
  static const Color greenLightColor = Color(0x8E9AFFB8);
  static const Color blueColor = Color(0xFF1D2B86);
  static const Color deepRedColor = Color(0xFF960808);
  static const Color textAreaColor = Color(0xFFF8FCFF);
  static const Color dividerColor = Color(0xFFC7C7C7);
  static const Color textAreaColor2 = Color(0xFFE8EBF0);
  static const Color containerColor4 = Color(0xFF929292);

  static const Color redColor = Color(0xFFFF0000);
  static const Color orangeColor1 = Color(0xFFFB7065);
  static const Color textGreyColor = Color(0xFF85899D);
  static const Color heightBorderColor = Color(0xFFE0E0E0);
  static const Color searchBorderColor = Color(0xFFFFFEFD);
  static const Color textAreaBorderColor = Color(0xFFE7E2E4);
  static const Color inactiveTrack = Color(0xFFD9D9D9);
  static const Color inactiveButton = Color(0xFFD9D9D9);
  static const Color nameColor = Color(0xFF63667E);
  static const Color degicColor = Color(0xFF7B7D87);
  static const Color titleColor = Color(0xFF484B5B);
  static const Color aboutTitleColor = Color(0xFF44485C);
  static const Color aboutDetailsColor = Color(0xFFF0F2F7);
  static const Color subTitleColor = Color(0xFFB5B6B9);
  static const Color backColor = Color(0xFF9095AC);
  static const Color whiteColor = Color(0xFFFFFFFF);
  static const Color grey30Color = Color(0xFF6A6A6A);
  static const Color toggleColor = Color(0xFFE8EAF0);
  static const Color inactiveScroll = Color(0xFFAFAFAF);

  static const Color textWhiteColor = Color(0xFFFFFFFF);
  static const Color textTitleColor = Color(0xFF002B5B);
  static const Color textHintColor = Color(0xFF807B75);
  static const Color textGreenColor = Color(0xFFA1B17E);
  static const Color buttonBackgroundColor = Color(0xFFF1EADB);
  static const Color buttonDisableColor = Color(0xFF8D8D8D);
  static const Color greyTone1 = Color(0xFF636A70);
  static const Color textGreyColor2 = Color(0xFF676360);
  static const Color textGreyColor3 = Color(0xFFAEAEB2);
  static const Color textSendColor = Color(0xFF806E6A);
  static const Color whiteTextColor = Color(0xFFEEEEEE);
  static const Color whiteLiteColor = Color(0xFFBABABA);
  static const Color blackLiteColor = Color(0xFF0B0B0B);
  static const Color textareaColor = Color(0xFFFDFDFE);
  static const Color borderareaColor = Color(0xFFE7E9ED);
  static const Color background1Color = Color(0xFFEAEAEA);

  // static const Color backColor = Color(0xFFECF0FF);
  static const Color black25 = Color(0x40000000);
  static const Color greyBC = Color(0xFFBCBCC0);
  static const Color darkGrey = Color(0xFF343537);
  static const Color subTitleGrey = Color(0xFF8E8E93);

  static const Color greyTone = Color(0xFF676360);
  static const Color beigeBrown = Color(0xFFC4AD8E);
  static const Color lightBeige = Color(0xFFF1E9DB);
  static const Color softBeige = Color(0xFFE6DBC9);

  static const Color deepred = Color(0xFFCA0000);
  static const Color vividBlue = Color(0xFF1D85FF);
  static const Color mutedBlueGrey = Color(0xFF767D95);

  static const Color lightBlue = Color(0xFFF3F6FF);
  static const Color softRed = Color(0xFFC94C6D);
  static const Color palePink = Color(0xFFD7AFB9);
  static const Color black12 = Color(0x1F000000);
  static const Color veryLightGray = Color(0xFFFDFDFE);
  static const Color lightGrey = Color(0xFFE0E0E0);
  static const Color softBlueGrey = Color(0xFFA8AAB9);
  static const Color lightBlueBackground = Color(0xFFF0F2F8);
}
